### ISSUE TITLE
module 'argparse' has no attribute 'BooleanOptionalAction'

### ISSUE THREAD

**Issue by Precko** [LetPeopleWork/MonteCarloCSV#1]
**Describe the bug**
After having successfully installed the module, when trying to run `montecarlocsv ` in Windows Powershell, I get the following error message:

```
Error while executing montecarloscsv:
module 'argparse' has no attribute 'BooleanOptionalAction'

```

**Expected behavior**
When not supplied with any parameters, the module should use the default values and generate an ExampleFile.csv with dummy values to the current directory.

**Configuration**
_Please upload your csv file and share your configuration, so we can reproduce the bug._
No parameters used, no csv got.

**Comment by huserben** [comment]
Hi @Precko 

thanks for reporting this problem (and following the template - much appreciated!).

It seems like one functionality of the `argparse` library (BooleanOptionalAction) was added only in python version 3.9.

If you run `python --version` I believe you'll get something that is 3.8 or lower.
While I try to figure out how I can make this constraint more visible, I believe upgrading your python to the latest version (3.12.4 according to https://www.python.org/downloads/ ) should solve the problem.

Could you try this out?

**Comment by huserben** [comment]
I've specified the dependency now more clearly, so the installation *should* fail if you don't have python in version 3.9 or higher. It's also listed in the docs:
![image](https://github.com/user-attachments/assets/e2b46d79-60ef-4485-9f34-0db225103e66)


You can [download the latest version (0.9.4)](https://pypi.org/project/montecarlocsv/0.9.4/) if you want to check. However, you still still need to install a newer python version (assuming that this is the problem of course).

**Comment by Precko** [comment]
Hello @huserben , thanks for the quick response.
After upgrading to Python 3.12 (and downloading the latest version of your app) the script runs properly with the default parameters.
I'm going to try it out with some live data next week.
Thanks again for your urgent help with it :)
